"""empty message

Revision ID: fae8912bf04b
Revises: 7194757f95e0
Create Date: 2021-05-07 19:58:08.088416

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'fae8912bf04b'
down_revision = '7194757f95e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('current', sa.Column('parent_1', sa.Integer(), nullable=False))
    op.drop_constraint('current_ibfk_1', 'current', type_='foreignkey')
    op.create_foreign_key(None, 'current', 'parent', ['parent_1'], ['id'])
    op.drop_column('current', 'parents')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('current', sa.Column('parents', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'current', type_='foreignkey')
    op.create_foreign_key('current_ibfk_1', 'current', 'parent', ['parents'], ['id'])
    op.drop_column('current', 'parent_1')
    # ### end Alembic commands ###
